events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://group_app:1337;
        }

        location /pgadmin {
            proxy_pass http://group_admin:80;
        }
    }
}